export const MAPPING =
  [
    {
      'id': '256863130',
      'twitterName': 'udcvr64',
      'personId': 4154,
      'name': 'Jean-Luc Addor',
      'number': 3055,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '3257088023',
      'twitterName': 'SibelArslanBS',
      'personId': 4184,
      'name': 'Sibel Arslan',
      'number': 3058,
      'council': 'NR',
      'party': 'BastA',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4155,
      'name': 'Beat Arnold',
      'number': 3057,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '219076403',
      'twitterName': 'anbarrile',
      'personId': 4203,
      'name': 'Angelo Barrile',
      'number': 3104,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '43504217',
      'twitterName': 'bendahan',
      'personId': 4213,
      'name': 'Samuel Bendahan',
      'number': 3114,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '3329760406',
      'twitterName': 'HUBigler',
      'personId': 4209,
      'name': 'Hans-Ulrich Bigler',
      'number': 3110,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4215,
      'name': 'Hansjörg Brunner',
      'number': 3116,
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 724,
      'name': 'Daniel Brélaz',
      'number': 2023,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': '724584142344695808',
      'twitterName': 'michael_buffat',
      'personId': 4156,
      'name': 'Michaël Buffat',
      'number': 3062,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4195,
      'name': 'Laurence Fehlmann Rielle',
      'number': 3071,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '182760916',
      'twitterName': 'FrickerJonas',
      'personId': 4185,
      'name': 'Jonas Fricker',
      'number': 3072,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': '107053461',
      'twitterName': 'minlimarti',
      'personId': 4197,
      'name': 'Min Li Marti',
      'number': 3084,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '20442734',
      'twitterName': 'nantermod',
      'personId': 4193,
      'name': 'Philippe Nantermod',
      'number': 3088,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '385293664',
      'twitterName': 'BabaSteinemann',
      'personId': 4174,
      'name': 'Barbara Steinemann',
      'number': 3096,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4053,
      'name': 'Thomas Aeschi',
      'number': 2758,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4107,
      'name': 'Cesla Amarelle',
      'number': 3014,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '3302607988',
      'twitterName': 'th_ammann',
      'personId': 4180,
      'name': 'Thomas Ammann',
      'number': 3056,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '280789941',
      'twitterName': 'M_Aebischer',
      'personId': 4049,
      'name': 'Matthias Aebischer',
      'number': 2760,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3867,
      'name': 'Andreas Aebi',
      'number': 2670,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4161,
      'name': 'Andreas Glarner',
      'number': 3074,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '235081966',
      'twitterName': 'Agmur',
      'personId': 4181,
      'name': 'Andrea Gmür-Schönenberger',
      'number': 3075,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '278262326',
      'twitterName': 'BarazzoneG',
      'personId': 4138,
      'name': 'Guillaume Barazzone',
      'number': 3040,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4214,
      'name': 'Niklaus-Samuel Gugger',
      'number': 3115,
      'party': 'EVP',
    },
    {
      'id': '50047040',
      'twitterName': 'JayBadran',
      'personId': 4058,
      'name': 'Jacqueline Badran',
      'number': 2762,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '3096244845',
      'twitterName': 'AmaudruzCeline',
      'personId': 4090,
      'name': 'Céline Amaudruz',
      'number': 2796,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4187,
      'name': 'Philippe Bauer',
      'number': 3059,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4165,
      'name': 'Barbara Keller-Inhelder',
      'number': 3081,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4166,
      'name': 'Roger Köppel',
      'number': 3082,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '3221526790',
      'twitterName': 'Martin_Baeumle',
      'personId': 1138,
      'name': 'Martin Bäumle',
      'number': 2585,
      'council': 'NR',
      'party': 'GLP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4030,
      'name': 'Prisca Birrer-Heimo',
      'number': 2743,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4102,
      'name': 'Kathrin Bertschy',
      'number': 3016,
      'council': 'NR',
      'party': 'GLP',
    },
    {
      'id': '743779500341792768',
      'twitterName': 'seilergraf',
      'personId': 4199,
      'name': 'Priska Seiler Graf',
      'number': 3094,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '556256043',
      'twitterName': 'SaSollberger',
      'personId': 4173,
      'name': 'Sandra Sollberger',
      'number': 3095,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4157,
      'name': 'Manfred Bühler',
      'number': 3063,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '2154083999',
      'twitterName': 'e_ettlin',
      'personId': 4206,
      'name': 'Erich Ettlin',
      'number': 3107,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 74,
      'name': 'Christoph Eymann',
      'number': 2287,
      'council': 'NR',
      'party': 'LDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4032,
      'name': 'Beat Jans',
      'number': 2745,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '327254073',
      'twitterName': 'Ch_Lohr',
      'personId': 4118,
      'name': 'Christian Lohr',
      'number': 3024,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '1228066279',
      'twitterName': 'nmasshardt',
      'personId': 4130,
      'name': 'Nadine Masshardt',
      'number': 3034,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4168,
      'name': 'Jacques Nicolet',
      'number': 3089,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '323132835',
      'twitterName': 'LorenzQuadri',
      'personId': 4046,
      'name': 'Lorenzo Quadri',
      'number': 2752,
      'council': 'NR',
      'party': 'Lega',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4143,
      'name': 'Rebecca Ana Ruiz',
      'number': 3045,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '263582303',
      'twitterName': 'Elisabeth_S_S',
      'personId': 4040,
      'name': 'Elisabeth Schneider-Schneiter',
      'number': 2748,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '14077586',
      'twitterName': 'bastiengirod',
      'personId': 3882,
      'name': 'Bastien Girod',
      'number': 2685,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4216,
      'name': 'Diana Gutjahr',
      'number': 3117,
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4137,
      'name': 'Roger Golay',
      'number': 3039,
      'council': 'NR',
      'party': 'MCG',
    },
    {
      'id': '3354760547',
      'twitterName': 'AliceGlauser',
      'personId': 3883,
      'name': 'Alice Glauser-Zufferey',
      'number': 2686,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '816301993799155712',
      'twitterName': 'Chrige_Haesler',
      'personId': 4149,
      'name': 'Christine Häsler',
      'number': 3051,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3886,
      'name': 'Hans Grunder',
      'number': 2689,
      'council': 'NR',
      'party': 'BDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1135,
      'name': 'Adrian Amstutz',
      'number': 2584,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '1543019749',
      'twitterName': 'LorenzHess',
      'personId': 4094,
      'name': 'Lorenz Hess',
      'number': 2799,
      'council': 'NR',
      'party': 'BDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4098,
      'name': 'Peter Keller',
      'number': 3013,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '2982472295',
      'twitterName': 'HansjoergKnecht',
      'personId': 4114,
      'name': 'Hansjörg Knecht',
      'number': 3021,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4056,
      'name': 'Daniel Fässler',
      'number': 2767,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '2431017296',
      'twitterName': 'Werner_Hoesli',
      'personId': 4145,
      'name': 'Werner Hösli',
      'number': 3047,
      'council': 'SR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4144,
      'name': 'Thomas Matter',
      'number': 3046,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4088,
      'name': 'Isidor Baumann',
      'number': 2793,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': '2449367689',
      'twitterName': 'GMarchand_Balet',
      'personId': 4183,
      'name': 'Géraldine Marchand-Balet',
      'number': 3083,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '350198606',
      'twitterName': 'RobiPanta',
      'personId': 4073,
      'name': 'Roberta Pantani',
      'number': 2773,
      'council': 'NR',
      'party': 'Lega',
    },
    {
      'id': '217706717',
      'twitterName': 'eviallemann',
      'personId': 1131,
      'name': 'Evi Allemann',
      'number': 2583,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '2832533567',
      'twitterName': 'RiederBeat',
      'personId': 4204,
      'name': 'Beat Rieder',
      'number': 3105,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4202,
      'name': 'Regine Sauter',
      'number': 3103,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4146,
      'name': 'Heinz Siegenthaler',
      'number': 3048,
      'council': 'NR',
      'party': 'BDP',
    },
    {
      'id': '61431883',
      'twitterName': 'SVPBrunner',
      'personId': 307,
      'name': 'Toni Brunner',
      'number': 2372,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '605639477',
      'twitterName': 'fgrueter',
      'personId': 4162,
      'name': 'Franz Grüter',
      'number': 3076,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '3240586961',
      'twitterName': 'ThierryBurkart',
      'personId': 4189,
      'name': 'Thierry Burkart',
      'number': 3065,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4025,
      'name': 'Roland Rino Büchel',
      'number': 2740,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '2452772930',
      'twitterName': 'martin_candinas',
      'personId': 4070,
      'name': 'Martin Candinas',
      'number': 2770,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4142,
      'name': 'Beat Walti',
      'number': 3044,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4201,
      'name': 'Denis de la Reussille',
      'number': 3068,
      'council': 'NR',
      'party': 'PdA',
    },
    {
      'id': '1017350089',
      'twitterName': 'Yvette67Yvette',
      'personId': 3876,
      'name': 'Yvette Estermann',
      'number': 2679,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '123362849',
      'twitterName': 'beatflach',
      'personId': 4059,
      'name': 'Beat Flach',
      'number': 2765,
      'council': 'NR',
      'party': 'GLP',
    },
    {
      'id': '353662120',
      'twitterName': 'ThomasBurgherr',
      'personId': 4158,
      'name': 'Thomas Burgherr',
      'number': 3064,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '2341633765',
      'twitterName': 'MajaIngold',
      'personId': 4031,
      'name': 'Maja Ingold',
      'number': 2744,
      'council': 'NR',
      'party': 'EVP',
    },
    {
      'id': '2696249536',
      'twitterName': 'claufriedl',
      'personId': 4131,
      'name': 'Claudia Friedl',
      'number': 3035,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '2822483402',
      'twitterName': 'BenoitGenecand',
      'personId': 4191,
      'name': 'Benoît Genecand',
      'number': 3073,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4071,
      'name': 'Urs Gasche',
      'number': 2764,
      'council': 'NR',
      'party': 'BDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3880,
      'name': 'Andrea Martina Geissbühler',
      'number': 2683,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4140,
      'name': 'Giovanni Merlini',
      'number': 3042,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '603431624',
      'twitterName': 'Damian_Mueller_',
      'personId': 4207,
      'name': 'Damian Müller',
      'number': 3108,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '2991955251',
      'twitterName': 'YvesNidegger',
      'personId': 3898,
      'name': 'Yves Nidegger',
      'number': 2701,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4169,
      'name': 'Pierre-André Page',
      'number': 3090,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '190944081',
      'twitterName': 'NatalieRickli',
      'personId': 3902,
      'name': 'Natalie Rickli',
      'number': 2705,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1137,
      'name': 'Walter Müller',
      'number': 2617,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1119,
      'name': 'Jean-François Rime',
      'number': 2627,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4084,
      'name': 'Bruno Pezzatti',
      'number': 2784,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4170,
      'name': 'Franz Ruppen',
      'number': 3091,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '50444931',
      'twitterName': 'cwasi',
      'personId': 3912,
      'name': 'Christian Wasserfallen',
      'number': 2715,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '485885985',
      'twitterName': 'ManuelTornare',
      'personId': 4113,
      'name': 'Manuel Tornare',
      'number': 3007,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '3063932104',
      'twitterName': 'hansuelivogt',
      'personId': 4176,
      'name': 'Hans-Ueli Vogt',
      'number': 3098,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4179,
      'name': 'David Zuberbühler',
      'number': 3102,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '14675346',
      'twitterName': 'bglaettli',
      'personId': 4093,
      'name': 'Balthasar Glättli',
      'number': 3003,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': '458597614',
      'twitterName': 'MullerAltermatt',
      'personId': 4063,
      'name': 'Stefan Müller-Altermatt',
      'number': 2771,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '444935177',
      'twitterName': 'idamicha',
      'personId': 1337,
      'name': 'Ida Glanzmann-Hunkeler',
      'number': 2657,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4054,
      'name': 'Albert Vitali',
      'number': 2761,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '2536865558',
      'twitterName': 'BaGysi',
      'personId': 4121,
      'name': 'Barbara Gysi',
      'number': 3026,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4096,
      'name': 'Alois Gmür',
      'number': 3001,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '2527505330',
      'twitterName': 'AlfredHeer',
      'personId': 3887,
      'name': 'Alfred Heer',
      'number': 2690,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4103,
      'name': 'Markus Hausammann',
      'number': 3002,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '1077680574',
      'twitterName': 'HurterThomas',
      'personId': 3890,
      'name': 'Thomas Hurter',
      'number': 2693,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '815578430',
      'twitterName': 'MaireJack',
      'personId': 4018,
      'name': 'Jacques-André Maire',
      'number': 2738,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '716002872',
      'twitterName': 'JauslinMatthias',
      'personId': 4208,
      'name': 'Matthias Samuel Jauslin',
      'number': 3109,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4153,
      'name': 'Peter Hegglin',
      'number': 3053,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': '1940472746',
      'twitterName': 'ClaudeBegle',
      'personId': 4182,
      'name': 'Claude Béglé',
      'number': 3060,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1141,
      'name': 'Philipp Müller',
      'number': 2616,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '780565772',
      'twitterName': 'MartinaMunz',
      'personId': 4134,
      'name': 'Martina Munz',
      'number': 3036,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4045,
      'name': 'Corrado Pardini',
      'number': 2751,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '373194785',
      'twitterName': 'FredericBorloz',
      'personId': 4188,
      'name': 'Frédéric Borloz',
      'number': 3061,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3872,
      'name': 'Jacques Bourgeois',
      'number': 2675,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '244437560',
      'twitterName': 'jcschwaab',
      'personId': 4115,
      'name': 'Jean Christophe Schwaab',
      'number': 3020,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '289393019',
      'twitterName': 'marcochiesa74',
      'personId': 4159,
      'name': 'Marco Chiesa',
      'number': 3067,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4200,
      'name': 'Duri Campell',
      'number': 3066,
      'council': 'NR',
      'party': 'BDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4051,
      'name': 'Thomas de Courten',
      'number': 2757,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '2882434546',
      'twitterName': 'Marcel_Dobler',
      'personId': 4190,
      'name': 'Marcel Dobler',
      'number': 3070,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4110,
      'name': 'Hans Egloff',
      'number': 3005,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4160,
      'name': 'Marcel Dettling',
      'number': 3069,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4151,
      'name': 'Josef Dittli',
      'number': 3052,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '888380018673545216',
      'twitterName': 'Thomas_Egger_NR',
      'personId': 4212,
      'name': 'Thomas Egger',
      'number': 3113,
      'council': 'NR',
      'party': 'CSPO',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4052,
      'name': 'Markus Ritter',
      'number': 2754,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4077,
      'name': 'Olivier Feller',
      'number': 2789,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3878,
      'name': 'Sylvia Flückiger-Bäni',
      'number': 2681,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '271068328',
      'twitterName': 'ybuttet',
      'personId': 4086,
      'name': 'Yannick Buttet',
      'number': 2790,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3910,
      'name': 'Erich von Siebenthal',
      'number': 2713,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '2870723938',
      'twitterName': 'adelethorens',
      'personId': 3907,
      'name': 'Adèle Thorens Goumaz',
      'number': 2710,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4192,
      'name': 'Hermann Hess',
      'number': 3079,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '21436172',
      'twitterName': 'cedricwermuth',
      'personId': 4057,
      'name': 'Cédric Wermuth',
      'number': 2759,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '62798697',
      'twitterName': 'Erich_Hess',
      'personId': 4163,
      'name': 'Erich Hess',
      'number': 3078,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '1947128240',
      'twitterName': 'Beat_Vonlanthen',
      'personId': 4205,
      'name': 'Beat Vonlanthen',
      'number': 3106,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': '847717320',
      'twitterName': 'MarinaCarobbio',
      'personId': 3830,
      'name': 'Marina Carobbio Guscetti',
      'number': 2666,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '246714911',
      'twitterName': 'EdithGraf',
      'personId': 1295,
      'name': 'Edith Graf-Litscher',
      'number': 2652,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '627501106',
      'twitterName': 'DdeBuman',
      'personId': 1124,
      'name': 'Dominique de Buman',
      'number': 2593,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4152,
      'name': 'Hans Wicki',
      'number': 3054,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 61,
      'name': 'Verena Diener Lenz',
      'number': 2044,
      'council': 'SR',
      'party': 'GLP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4065,
      'name': 'Nadja Pieren',
      'number': 2781,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '109517535',
      'twitterName': 'HPPortmann',
      'personId': 4141,
      'name': 'Hans-Peter Portmann',
      'number': 3043,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '3070292500',
      'twitterName': 'DorisFiala',
      'personId': 3877,
      'name': 'Doris Fiala',
      'number': 2680,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '3290133496',
      'twitterName': 'engler_stefan',
      'personId': 4055,
      'name': 'Stefan Engler',
      'number': 2768,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4042,
      'name': 'Sebastian Frehner',
      'number': 2750,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '35465127',
      'twitterName': 'hhiltpold',
      'personId': 3888,
      'name': 'Hugues Hiltpold',
      'number': 2691,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4175,
      'name': 'Mauro Tuena',
      'number': 3097,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4135,
      'name': 'Raymond Clottu',
      'number': 3037,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '617269323',
      'twitterName': 'GraberKonrad',
      'personId': 3921,
      'name': 'Konrad Graber',
      'number': 2724,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4062,
      'name': 'Karin Keller-Sutter',
      'number': 2769,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '546752881',
      'twitterName': 'UGiezendanner',
      'personId': 91,
      'name': 'Ulrich Giezendanner',
      'number': 2292,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '778644518',
      'twitterName': 'NordmannRoger',
      'personId': 1279,
      'name': 'Roger Nordmann',
      'number': 2648,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4139,
      'name': 'Thomas Hefti',
      'number': 3041,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '2860664668',
      'twitterName': 'RuthHumbel',
      'personId': 1071,
      'name': 'Ruth Humbel',
      'number': 2580,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '113616426',
      'twitterName': 'BernhardGuhl',
      'personId': 4082,
      'name': 'Bernhard Guhl',
      'number': 2785,
      'council': 'NR',
      'party': 'BDP',
    },
    {
      'id': '1052528581',
      'twitterName': 'enussbi',
      'personId': 3899,
      'name': 'Eric Nussbaumer',
      'number': 2702,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '222903677',
      'twitterName': 'ChristianImark',
      'personId': 4164,
      'name': 'Christian Imark',
      'number': 3080,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '26531313',
      'twitterName': 'lukasreimann',
      'personId': 3901,
      'name': 'Lukas Reimann',
      'number': 2704,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1108,
      'name': 'Guy Parmelin',
      'number': 2621,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '621159422',
      'twitterName': 'Valerie_Piller',
      'personId': 4109,
      'name': 'Valérie Piller Carrard',
      'number': 3009,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1148,
      'name': 'Géraldine Savary',
      'number': 2629,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '3428301377',
      'twitterName': 'OliFrancais',
      'personId': 3879,
      'name': 'Olivier Français',
      'number': 2682,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '3133285757',
      'twitterName': 'WernerSalzmann',
      'personId': 4172,
      'name': 'Werner Salzmann',
      'number': 3092,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1318,
      'name': 'Louis Schelbert',
      'number': 2654,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 801,
      'name': 'Fabio Abate',
      'number': 2565,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4177,
      'name': 'Bruno Walliser',
      'number': 3099,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '3374457514',
      'twitterName': 'nr_mayagraf',
      'personId': 806,
      'name': 'Maya Graf',
      'number': 2569,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': '155823857',
      'twitterName': 'IsabelleMoret',
      'personId': 1346,
      'name': 'Isabelle Moret',
      'number': 2660,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '2881577681',
      'twitterName': 'meyer_mattea',
      'personId': 4198,
      'name': 'Mattea Meyer',
      'number': 3087,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3885,
      'name': 'Jean-Pierre Grin',
      'number': 2688,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4097,
      'name': 'Leo Müller',
      'number': 3012,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '2948791281',
      'twitterName': 'th_hardegger',
      'personId': 4061,
      'name': 'Thomas Hardegger',
      'number': 2763,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '67100346',
      'twitterName': 'beaheim',
      'personId': 1156,
      'name': 'Bea Heim',
      'number': 2601,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4106,
      'name': 'Martin Naef',
      'number': 3018,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '196646702',
      'twitterName': 'PirminBischof',
      'personId': 3871,
      'name': 'Pirmin Bischof',
      'number': 2674,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4100,
      'name': 'Albert Rösti',
      'number': 3010,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 354,
      'name': 'Silva Semadeni',
      'number': 2417,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '2899280753',
      'twitterName': 'uschneiderschue',
      'personId': 4123,
      'name': 'Ursula Schneider Schüttel',
      'number': 3028,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3865,
      'name': 'Jean-François Steiert',
      'number': 2669,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '2226700633',
      'twitterName': 'MarianneStreiff',
      'personId': 4036,
      'name': 'Marianne Streiff-Feller',
      'number': 2747,
      'council': 'NR',
      'party': 'EVP',
    },
    {
      'id': '3301771943',
      'twitterName': 'LaurentWehrli',
      'personId': 4194,
      'name': 'Laurent Wehrli',
      'number': 3100,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '121068845',
      'twitterName': 'zac1967',
      'personId': 4178,
      'name': 'Claudio Zanetti',
      'number': 3101,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3918,
      'name': 'Werner Luginbühl',
      'number': 2721,
      'council': 'SR',
      'party': 'BDP',
    },
    {
      'id': '227087638',
      'twitterName': 'yferi',
      'personId': 4069,
      'name': 'Yvonne Feri',
      'number': 2777,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '761741430',
      'twitterName': 'LandoltMartin',
      'personId': 4008,
      'name': 'Martin Landolt',
      'number': 2735,
      'council': 'NR',
      'party': 'BDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1111,
      'name': 'Felix Müri',
      'number': 2618,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '1360306513',
      'twitterName': 'BulliardMarbach',
      'personId': 4101,
      'name': 'Christine Bulliard-Marbach',
      'number': 3017,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4167,
      'name': 'Magdalena Martullo-Blocher',
      'number': 3085,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '406232148',
      'twitterName': 'MathiasReynard',
      'personId': 4091,
      'name': 'Mathias Reynard',
      'number': 2795,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4125,
      'name': 'Gregor Rutz',
      'number': 3030,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1159,
      'name': 'Pirmin Schwander',
      'number': 2631,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '1530247224',
      'twitterName': 'RegulaRytz',
      'personId': 4095,
      'name': 'Regula Rytz',
      'number': 3000,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4085,
      'name': 'Karl Vogler',
      'number': 2787,
      'council': 'NR',
      'party': 'csp-ow',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4068,
      'name': 'Roland Eberle',
      'number': 2774,
      'council': 'SR',
      'party': 'SVP',
    },
    {
      'id': '619225869',
      'twitterName': 'fderder',
      'personId': 4079,
      'name': 'Fathi Derder',
      'number': 2788,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '45513818',
      'twitterName': 'SchmidFederer',
      'personId': 3904,
      'name': 'Barbara Schmid-Federer',
      'number': 2707,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '157431387',
      'twitterName': 'CarloSommaruga',
      'personId': 1120,
      'name': 'Carlo Sommaruga',
      'number': 2632,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '365423665',
      'twitterName': 'PetraGoessi',
      'personId': 4116,
      'name': 'Petra Gössi',
      'number': 3023,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 519,
      'name': 'Hansjörg Walter',
      'number': 2541,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '84155033',
      'twitterName': 'zanettiroberto',
      'personId': 525,
      'name': 'Roberto Zanetti',
      'number': 2546,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1142,
      'name': 'Walter Wobmann',
      'number': 2638,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '607353825',
      'twitterName': 'ada_marra',
      'personId': 3923,
      'name': 'Ada Marra',
      'number': 2726,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '3039132947',
      'twitterName': 'BrandHeinz',
      'personId': 4067,
      'name': 'Heinz Brand',
      'number': 2772,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '50262858',
      'twitterName': 'MarcoRomanoPPD',
      'personId': 4120,
      'name': 'Marco Romano',
      'number': 3025,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4217,
      'name': 'Rocco Cattaneo',
      'number': 3118,
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4074,
      'name': 'Pierre-Alain Fridez',
      'number': 2778,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '2841156604',
      'twitterName': 'TimGuldimann',
      'personId': 4196,
      'name': 'Tim Guldimann',
      'number': 3077,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '2613366038',
      'twitterName': 'ChantalGallade',
      'personId': 1125,
      'name': 'Chantal Galladé',
      'number': 2597,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '463149099',
      'twitterName': 'Juerg_Grossen',
      'personId': 4083,
      'name': 'Jürg Grossen',
      'number': 2786,
      'council': 'NR',
      'party': 'GLP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4087,
      'name': 'Jean-Paul Gschwind',
      'number': 2798,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4186,
      'name': 'Lisa Mazzone',
      'number': 3086,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3895,
      'name': 'Christian Lüscher',
      'number': 2698,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1345,
      'name': 'Thomas Müller',
      'number': 2661,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '303319566',
      'twitterName': 'SchenkerSilvia',
      'personId': 1129,
      'name': 'Silvia Schenker',
      'number': 2630,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '4702673004',
      'twitterName': 'SchneeDani67',
      'personId': 4060,
      'name': 'Daniela Schneeberger',
      'number': 2766,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3897,
      'name': 'Tiana Angelina Moser',
      'number': 2700,
      'council': 'NR',
      'party': 'GLP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4112,
      'name': 'Thomas Minder',
      'number': 3019,
      'council': 'SR',
      'party': '-',
    },
    {
      'id': '72560162',
      'twitterName': 'Violapamherd',
      'personId': 1288,
      'name': 'Viola Amherd',
      'number': 2646,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 471,
      'name': 'Felix Gutzwiller',
      'number': 2495,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 224,
      'name': 'Alexander Tschäppät',
      'number': 2328,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 477,
      'name': 'Claude Janiak',
      'number': 2501,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '2536784770',
      'twitterName': 'RobertCramer_GE',
      'personId': 3914,
      'name': 'Robert Cramer',
      'number': 2717,
      'council': 'SR',
      'party': 'GPS',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1147,
      'name': 'Margret Kiener Nellen',
      'number': 2608,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3905,
      'name': 'Roberto Schmidt',
      'number': 2708,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '991720068',
      'twitterName': 'fregazzi',
      'personId': 4072,
      'name': 'Fabio Regazzi',
      'number': 2776,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '3130690545',
      'twitterName': 'QuadrantiR',
      'personId': 4066,
      'name': 'Rosmarie Quadranti',
      'number': 2779,
      'council': 'NR',
      'party': 'BDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4124,
      'name': 'Peter Schilliger',
      'number': 3029,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '3295223895',
      'twitterName': 'RaphaelComteCE',
      'personId': 4026,
      'name': 'Raphaël Comte',
      'number': 2741,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '93878848',
      'twitterName': 'KathyRiklin',
      'personId': 502,
      'name': 'Kathy Riklin',
      'number': 2525,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '304379532',
      'twitterName': 'RuediNoser',
      'personId': 1153,
      'name': 'Ruedi Noser',
      'number': 2619,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3831,
      'name': 'Ivo Bischofberger',
      'number': 2667,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 514,
      'name': 'Jürg Stahl',
      'number': 2536,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3931,
      'name': 'Thomas Weibel',
      'number': 2728,
      'council': 'NR',
      'party': 'GLP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1267,
      'name': 'Hans Stöckli',
      'number': 2647,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '241509277',
      'twitterName': 'PascaleBruderer',
      'personId': 823,
      'name': 'Pascale Bruderer Wyss',
      'number': 2573,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1104,
      'name': 'Jakob Büchler',
      'number': 2588,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '149008275',
      'twitterName': 'I_Chevalley',
      'personId': 4108,
      'name': 'Isabelle Chevalley',
      'number': 3604,
      'council': 'NR',
      'party': 'GLP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1122,
      'name': 'Kurt Fluri',
      'number': 2594,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 321,
      'name': 'Peter Föhn',
      'number': 2385,
      'council': 'SR',
      'party': 'SVP',
    },
    {
      'id': '1307125520',
      'twitterName': 'verenaherzog',
      'personId': 4129,
      'name': 'Verena Herzog',
      'number': 3033,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '75777484',
      'twitterName': 'PhilippHadorn',
      'personId': 4076,
      'name': 'Philipp Hadorn',
      'number': 2792,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '270609583',
      'twitterName': 'ignaziocassis',
      'personId': 3828,
      'name': 'Ignazio Cassis',
      'number': 2664,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 825,
      'name': 'Hannes Germann',
      'number': 2575,
      'council': 'SR',
      'party': 'SVP',
    },
    {
      'id': '529478391',
      'twitterName': 'PaulRechsteiner',
      'personId': 172,
      'name': 'Paul Rechsteiner',
      'number': 2143,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4078,
      'name': 'Martin Schmid',
      'number': 2783,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '226922317',
      'twitterName': 'ChristaMarkwald',
      'personId': 1139,
      'name': 'Christa Markwalder',
      'number': 2614,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '40872955',
      'twitterName': 'ChristianLevrat',
      'personId': 1150,
      'name': 'Christian Levrat',
      'number': 2613,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '3246291543',
      'twitterName': 'danieljositsch',
      'personId': 3891,
      'name': 'Daniel Jositsch',
      'number': 2694,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '132899636',
      'twitterName': 'HaeberliKollerB',
      'personId': 1106,
      'name': 'Brigitte Häberli-Koller',
      'number': 2600,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3916,
      'name': 'Claude Hêche',
      'number': 2719,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 466,
      'name': 'Anita Fetz',
      'number': 2061,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '379014467',
      'twitterName': 'votrevoix',
      'personId': 341,
      'name': 'Liliane Maury Pasquier',
      'number': 2405,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '3291242279',
      'twitterName': 'gerhardpfister',
      'personId': 1109,
      'name': 'Gerhard Pfister',
      'number': 2623,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3920,
      'name': 'Anne Seydoux-Christe',
      'number': 2723,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': '3064353419',
      'twitterName': 'maximilian_rei',
      'personId': 173,
      'name': 'Maximilian Reimann',
      'number': 2147,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '271271590',
      'twitterName': 'berberatdidier',
      'personId': 305,
      'name': 'Didier Berberat',
      'number': 2370,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 4064,
      'name': 'Joachim Eder',
      'number': 2780,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 1162,
      'name': 'Alex Kuprecht',
      'number': 2641,
      'council': 'SR',
      'party': 'SVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3875,
      'name': 'Corina Eichenberger-Walther',
      'number': 2678,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '350243582',
      'twitterName': 'LuziStamm',
      'personId': 214,
      'name': 'Luzi Stamm',
      'number': 2323,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '442685639',
      'twitterName': 'AndreaCaroniAR',
      'personId': 4075,
      'name': 'Andrea Caroni',
      'number': 2775,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '332184640',
      'twitterName': 'SusanneSlo',
      'personId': 487,
      'name': 'Susanne Leutenegger Oberholzer',
      'number': 2129,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '804958800',
      'twitterName': 'lombardi1956',
      'personId': 540,
      'name': 'Filippo Lombardi',
      'number': 2561,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': null,
      'twitterName': null,
      'personId': 3915,
      'name': 'Jean-René Fournier',
      'number': 2718,
      'council': 'SR',
      'party': 'CVP',
    },
  ]
