export const MAPPING =
  [
    {
      'id': '1530247224',
      'twitterName': 'RegulaRytz',
      'personId': 4095,
      'name': 'Regula Rytz',
      'number': 3000,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': '2536865558',
      'twitterName': 'BaGysi',
      'personId': 4121,
      'name': 'Barbara Gysi',
      'number': 3026,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '991720068',
      'twitterName': 'fregazzi',
      'personId': 4072,
      'name': 'Fabio Regazzi',
      'number': 2776,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '1228066279',
      'twitterName': 'nmasshardt',
      'personId': 4130,
      'name': 'Nadine Masshardt',
      'number': 3034,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '2527505330',
      'twitterName': 'AlfredHeer',
      'personId': 3887,
      'name': 'Alfred Heer',
      'number': 2690,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '621159422',
      'twitterName': 'Valerie_Piller',
      'personId': 4109,
      'name': 'Valérie Piller Carrard',
      'number': 3009,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '2948791281',
      'twitterName': 'th_hardegger',
      'personId': 4061,
      'name': 'Thomas Hardegger',
      'number': 2763,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '1360306513',
      'twitterName': 'BulliardMarbach',
      'personId': 4101,
      'name': 'Christine Bulliard-Marbach',
      'number': 3017,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '1543019749',
      'twitterName': 'LorenzHess',
      'personId': 4094,
      'name': 'Lorenz Hess',
      'number': 2799,
      'council': 'NR',
      'party': 'BDP',
    },
    {
      'id': '350198606',
      'twitterName': 'RobiPanta',
      'personId': 4073,
      'name': 'Roberta Pantani',
      'number': 2773,
      'council': 'NR',
      'party': 'Lega',
    },
    {
      'id': '365423665',
      'twitterName': 'PetraGoessi',
      'personId': 4116,
      'name': 'Petra Gössi',
      'number': 3023,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '227087638',
      'twitterName': 'yferi',
      'personId': 4069,
      'name': 'Yvonne Feri',
      'number': 2777,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '327254073',
      'twitterName': 'Ch_Lohr',
      'personId': 4118,
      'name': 'Christian Lohr',
      'number': 3024,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '271068328',
      'twitterName': 'ybuttet',
      'personId': 4086,
      'name': 'Yannick Buttet',
      'number': 2790,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '244437560',
      'twitterName': 'jcschwaab',
      'personId': 4115,
      'name': 'Jean Christophe Schwaab',
      'number': 3020,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '149008275',
      'twitterName': 'I_Chevalley',
      'personId': 4108,
      'name': 'Isabelle Chevalley',
      'number': 3604,
      'council': 'NR',
      'party': 'glp',
    },
    {
      'id': '123362849',
      'twitterName': 'beatflach',
      'personId': 4059,
      'name': 'Beat Flach',
      'number': 2765,
      'council': 'NR',
      'party': 'glp',
    },
    {
      'id': '780565772',
      'twitterName': 'MartinaMunz',
      'personId': 4134,
      'name': 'Martina Munz',
      'number': 3036,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '1052528581',
      'twitterName': 'enussbi',
      'personId': 3899,
      'name': 'Eric Nussbaumer',
      'number': 2702,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '190944081',
      'twitterName': 'NatalieRickli',
      'personId': 3902,
      'name': 'Natalie Rickli',
      'number': 2705,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '1077680574',
      'twitterName': 'HurterThomas',
      'personId': 3890,
      'name': 'Thomas Hurter',
      'number': 2693,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '2452772930',
      'twitterName': 'martin_candinas',
      'personId': 4070,
      'name': 'Martin Candinas',
      'number': 2770,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '1307125520',
      'twitterName': 'verenaherzog',
      'personId': 4129,
      'name': 'Verena Herzog',
      'number': 3033,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '485885985',
      'twitterName': 'ManuelTornare',
      'personId': 4113,
      'name': 'Manuel Tornare',
      'number': 3007,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '2341633765',
      'twitterName': 'MajaIngold',
      'personId': 4031,
      'name': 'Maja Ingold',
      'number': 2744,
      'council': 'NR',
      'party': 'EVP',
    },
    {
      'id': '280789941',
      'twitterName': 'M_Aebischer',
      'personId': 4049,
      'name': 'Matthias Aebischer',
      'number': 2760,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '2696249536',
      'twitterName': 'claufriedl',
      'personId': 4131,
      'name': 'Claudia Friedl',
      'number': 3035,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '217706717',
      'twitterName': 'eviallemann',
      'personId': 1131,
      'name': 'Evi Allemann',
      'number': 2583,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '607353825',
      'twitterName': 'ada_marra',
      'personId': 3923,
      'name': 'Ada Marra',
      'number': 2726,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '155823857',
      'twitterName': 'IsabelleMoret',
      'personId': 1346,
      'name': 'Isabelle Moret',
      'number': 2660,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '2870723938',
      'twitterName': 'adelethorens',
      'personId': 3907,
      'name': 'Adèle Thorens Goumaz',
      'number': 2710,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': '3428301377',
      'twitterName': 'OliFrancais',
      'personId': 3879,
      'name': 'Olivier Français',
      'number': 2682,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '107053461',
      'twitterName': 'minlimarti',
      'personId': 4197,
      'name': 'Min Li Marti',
      'number': 3084,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '75777484',
      'twitterName': 'PhilippHadorn',
      'personId': 4076,
      'name': 'Philipp Hadorn',
      'number': 2792,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '2870723938',
      'twitterName': 'adelethorens',
      'personId': 3907,
      'name': 'Adèle Thorens Goumaz',
      'number': 2710,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': '605639477',
      'twitterName': 'fgrueter',
      'personId': 4162,
      'name': 'Franz Grüter',
      'number': 3076,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '546752881',
      'twitterName': 'UGiezendanner',
      'personId': 91,
      'name': 'Ulrich Giezendanner',
      'number': 2292,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '121068845',
      'twitterName': 'zac1967',
      'personId': 4178,
      'name': 'Claudio Zanetti',
      'number': 3101,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '627501106',
      'twitterName': 'DdeBuman',
      'personId': 1124,
      'name': 'Dominique de Buman',
      'number': 2593,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '385293664',
      'twitterName': 'BabaSteinemann',
      'personId': 4174,
      'name': 'Barbara Steinemann',
      'number': 3096,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '3257088023',
      'twitterName': 'SibelArslanBS',
      'personId': 4184,
      'name': 'Sibel Arslan',
      'number': 3058,
      'council': 'NR',
      'party': 'BastA',
    },
    {
      'id': '219076403',
      'twitterName': 'anbarrile',
      'personId': 4203,
      'name': 'Angelo Barrile',
      'number': 3104,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '222903677',
      'twitterName': 'ChristianImark',
      'personId': 4164,
      'name': 'Christian Imark',
      'number': 3080,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '2154083999',
      'twitterName': 'e_ettlin',
      'personId': 4206,
      'name': 'Erich Ettlin',
      'number': 3107,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': '619225869',
      'twitterName': 'fderder',
      'personId': 4079,
      'name': 'Fathi Derder',
      'number': 2788,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '20442734',
      'twitterName': 'nantermod',
      'personId': 4193,
      'name': 'Philippe Nantermod',
      'number': 3088,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '235081966',
      'twitterName': 'Agmur',
      'personId': 4181,
      'name': 'Andrea Gmür-Schönenberger',
      'number': 3075,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '109517535',
      'twitterName': 'HPPortmann',
      'personId': 4141,
      'name': 'Hans-Peter Portmann',
      'number': 3043,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '270609583',
      'twitterName': 'ignaziocassis',
      'personId': 3828,
      'name': 'Ignazio Cassis',
      'number': 2664,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '2982472295',
      'twitterName': 'HansjoergKnecht',
      'personId': 4114,
      'name': 'Hansjörg Knecht',
      'number': 3021,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '2881577681',
      'twitterName': 'meyer_mattea',
      'personId': 4198,
      'name': 'Mattea Meyer',
      'number': 3087,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '3221526790',
      'twitterName': 'Martin_Baeumle',
      'personId': 1138,
      'name': 'Martin Bäumle',
      'number': 2585,
      'council': 'NR',
      'party': 'glp',
    },
    {
      'id': '3301771943',
      'twitterName': 'LaurentWehrli',
      'personId': 4194,
      'name': 'Laurent Wehrli',
      'number': 3100,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '761741430',
      'twitterName': 'LandoltMartin',
      'personId': 4008,
      'name': 'Martin Landolt',
      'number': 2735,
      'council': 'NR',
      'party': 'BDP',
    },
    {
      'id': '2899280753',
      'twitterName': 'uschneiderschue',
      'personId': 4123,
      'name': 'Ursula Schneider Schüttel',
      'number': 3028,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '3329760406',
      'twitterName': 'HUBigler',
      'personId': 4209,
      'name': 'Hans-Ulrich Bigler',
      'number': 3110,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '84155033',
      'twitterName': 'zanettiroberto',
      'personId': 525,
      'name': 'Roberto Zanetti',
      'number': 2546,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '332184640',
      'twitterName': 'SusanneSlo',
      'personId': 487,
      'name': 'Susanne Leutenegger Oberholzer',
      'number': 2129,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '1940472746',
      'twitterName': 'ClaudeBegle',
      'personId': 4182,
      'name': 'Claude Béglé',
      'number': 3060,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '2449367689',
      'twitterName': 'GMarchand_Balet',
      'personId': 4183,
      'name': 'Géraldine Marchand-Balet',
      'number': 3083,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '3295223895',
      'twitterName': 'RaphaelComteCE',
      'personId': 4026,
      'name': 'Raphaël Comte',
      'number': 2741,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '289393019',
      'twitterName': 'marcochiesa74',
      'personId': 4159,
      'name': 'Marco Chiesa',
      'number': 3067,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '2991955251',
      'twitterName': 'YvesNidegger',
      'personId': 3898,
      'name': 'Yves Nidegger',
      'number': 2701,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '3096244845',
      'twitterName': 'AmaudruzCeline',
      'personId': 4090,
      'name': 'Céline Amaudruz',
      'number': 2796,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '4702673004',
      'twitterName': 'SchneeDani67',
      'personId': 4060,
      'name': 'Daniela Schneeberger',
      'number': 2766,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '304379532',
      'twitterName': 'RuediNoser',
      'personId': 1153,
      'name': 'Ruedi Noser',
      'number': 2619,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '2860664668',
      'twitterName': 'RuthHumbel',
      'personId': 1071,
      'name': 'Ruth Humbel',
      'number': 2580,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '379014467',
      'twitterName': 'votrevoix',
      'personId': 341,
      'name': 'Liliane Maury Pasquier',
      'number': 2405,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '3064353419',
      'twitterName': 'maximilian_rei',
      'personId': 173,
      'name': 'Maximilian Reimann',
      'number': 2147,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '271271590',
      'twitterName': 'berberatdidier',
      'personId': 305,
      'name': 'Didier Berberat',
      'number': 2370,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '157431387',
      'twitterName': 'CarloSommaruga',
      'personId': 1120,
      'name': 'Carlo Sommaruga',
      'number': 2632,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '40872955',
      'twitterName': 'ChristianLevrat',
      'personId': 1150,
      'name': 'Christian Levrat',
      'number': 2613,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '815578430',
      'twitterName': 'MaireJack',
      'personId': 4018,
      'name': 'Jacques-André Maire',
      'number': 2738,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '603431624',
      'twitterName': 'Damian_Mueller_',
      'personId': 4207,
      'name': 'Damian Müller',
      'number': 3108,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '2226700633',
      'twitterName': 'MarianneStreiff',
      'personId': 4036,
      'name': 'Marianne Streiff-Feller',
      'number': 2747,
      'council': 'NR',
      'party': 'EVP',
    },
    {
      'id': '3063932104',
      'twitterName': 'hansuelivogt',
      'personId': 4176,
      'name': 'Hans-Ueli Vogt',
      'number': 3098,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '353662120',
      'twitterName': 'ThomasBurgherr',
      'personId': 4158,
      'name': 'Thomas Burgherr',
      'number': 3064,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '2822483402',
      'twitterName': 'BenoitGenecand',
      'personId': 4191,
      'name': 'Benoît Genecand',
      'number': 3073,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '62798697',
      'twitterName': 'Erich_Hess',
      'personId': 4163,
      'name': 'Erich Hess',
      'number': 3078,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '724584142344695808',
      'twitterName': 'michael_buffat',
      'personId': 4156,
      'name': 'Michaël Buffat',
      'number': 3062,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '2431017296',
      'twitterName': 'Werner_Hoesli',
      'personId': 4145,
      'name': 'Werner Hösli',
      'number': 3047,
      'council': 'SR',
      'party': 'SVP',
    },
    {
      'id': '50047040',
      'twitterName': 'JayBadran',
      'personId': 4058,
      'name': 'Jacqueline Badran',
      'number': 2762,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '93878848',
      'twitterName': 'KathyRiklin',
      'personId': 502,
      'name': 'Kathy Riklin',
      'number': 2525,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '14077586',
      'twitterName': 'bastiengirod',
      'personId': 3882,
      'name': 'Bastien Girod',
      'number': 2685,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': '3302607988',
      'twitterName': 'th_ammann',
      'personId': 4180,
      'name': 'Thomas Ammann',
      'number': 3056,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '463149099',
      'twitterName': 'Juerg_Grossen',
      'personId': 4083,
      'name': 'Jürg Grossen',
      'number': 2786,
      'council': 'NR',
      'party': 'glp',
    },
    {
      'id': '617269323',
      'twitterName': 'GraberKonrad',
      'personId': 3921,
      'name': 'Konrad Graber',
      'number': 2724,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': '529478391',
      'twitterName': 'PaulRechsteiner',
      'personId': 172,
      'name': 'Paul Rechsteiner',
      'number': 2143,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '2882434546',
      'twitterName': 'Marcel_Dobler',
      'personId': 4190,
      'name': 'Marcel Dobler',
      'number': 3070,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '45513818',
      'twitterName': 'SchmidFederer',
      'personId': 3904,
      'name': 'Barbara Schmid-Federer',
      'number': 2707,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '3039132947',
      'twitterName': 'BrandHeinz',
      'personId': 4067,
      'name': 'Heinz Brand',
      'number': 2772,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '50444931',
      'twitterName': 'cwasi',
      'personId': 3912,
      'name': 'Christian Wasserfallen',
      'number': 2715,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '2536784770',
      'twitterName': 'RobertCramer_GE',
      'personId': 3914,
      'name': 'Robert Cramer',
      'number': 2717,
      'council': 'SR',
      'party': 'GPS',
    },
    {
      'id': '458597614',
      'twitterName': 'MullerAltermatt',
      'personId': 4063,
      'name': 'Stefan Müller-Altermatt',
      'number': 2771,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '888380018673545216',
      'twitterName': 'Thomas_Egger_NR',
      'personId': 4212,
      'name': 'Thomas Egger',
      'number': 3113,
      'council': 'NR',
      'party': 'CSPO',
    },
    {
      'id': '804958800',
      'twitterName': 'lombardi1956',
      'personId': 540,
      'name': 'Filippo Lombardi',
      'number': 2561,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': '373194785',
      'twitterName': 'FredericBorloz',
      'personId': 4188,
      'name': 'Frédéric Borloz',
      'number': 3061,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '406232148',
      'twitterName': 'MathiasReynard',
      'personId': 4091,
      'name': 'Mathias Reynard',
      'number': 2795,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '778644518',
      'twitterName': 'NordmannRoger',
      'personId': 1279,
      'name': 'Roger Nordmann',
      'number': 2648,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '61431883',
      'twitterName': 'SVPBrunner',
      'personId': 307,
      'name': 'Toni Brunner',
      'number': 2372,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '3133285757',
      'twitterName': 'WernerSalzmann',
      'personId': 4172,
      'name': 'Werner Salzmann',
      'number': 3092,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '3354760547',
      'twitterName': 'AliceGlauser',
      'personId': 3883,
      'name': 'Alice Glauser-Zufferey',
      'number': 2686,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '716002872',
      'twitterName': 'JauslinMatthias',
      'personId': 4208,
      'name': 'Matthias Samuel Jauslin',
      'number': 3109,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '43504217',
      'twitterName': 'bendahan',
      'personId': 4213,
      'name': 'Samuel Bendahan',
      'number': 3114,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '3290133496',
      'twitterName': 'engler_stefan',
      'personId': 4055,
      'name': 'Stefan Engler',
      'number': 2768,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': '2841156604',
      'twitterName': 'TimGuldimann',
      'personId': 4196,
      'name': 'Tim Guldimann',
      'number': 3077,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '132899636',
      'twitterName': 'HaeberliKollerB',
      'personId': 1106,
      'name': 'Brigitte Häberli-Koller',
      'number': 2600,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': '743779500341792768',
      'twitterName': 'seilergraf',
      'personId': 4199,
      'name': 'Priska Seiler Graf',
      'number': 3094,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '444935177',
      'twitterName': 'idamicha',
      'personId': 1337,
      'name': 'Ida Glanzmann-Hunkeler',
      'number': 2657,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '350243582',
      'twitterName': 'LuziStamm',
      'personId': 214,
      'name': 'Luzi Stamm',
      'number': 2323,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '847717320',
      'twitterName': 'MarinaCarobbio',
      'personId': 3830,
      'name': 'Marina Carobbio Guscetti',
      'number': 2666,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '3070292500',
      'twitterName': 'DorisFiala',
      'personId': 3877,
      'name': 'Doris Fiala',
      'number': 2680,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '35465127',
      'twitterName': 'hhiltpold',
      'personId': 3888,
      'name': 'Hugues Hiltpold',
      'number': 2691,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '323132835',
      'twitterName': 'LorenzQuadri',
      'personId': 4046,
      'name': 'Lorenzo Quadri',
      'number': 2752,
      'council': 'NR',
      'party': 'Lega',
    },
    {
      'id': '241509277',
      'twitterName': 'PascaleBruderer',
      'personId': 823,
      'name': 'Pascale Bruderer Wyss',
      'number': 2573,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '278262326',
      'twitterName': 'BarazzoneG',
      'personId': 4138,
      'name': 'Guillaume Barazzone',
      'number': 3040,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '442685639',
      'twitterName': 'AndreaCaroniAR',
      'personId': 4075,
      'name': 'Andrea Caroni',
      'number': 2775,
      'council': 'SR',
      'party': 'FDP',
    },
    {
      'id': '67100346',
      'twitterName': 'beaheim',
      'personId': 1156,
      'name': 'Bea Heim',
      'number': 2601,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '3291242279',
      'twitterName': 'gerhardpfister',
      'personId': 1109,
      'name': 'Gerhard Pfister',
      'number': 2623,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '3374457514',
      'twitterName': 'nr_mayagraf',
      'personId': 806,
      'name': 'Maya Graf',
      'number': 2569,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': '2613366038',
      'twitterName': 'ChantalGallade',
      'personId': 1125,
      'name': 'Chantal Galladé',
      'number': 2597,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '303319566',
      'twitterName': 'SchenkerSilvia',
      'personId': 1129,
      'name': 'Silvia Schenker',
      'number': 2630,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '263582303',
      'twitterName': 'Elisabeth_S_S',
      'personId': 4040,
      'name': 'Elisabeth Schneider-Schneiter',
      'number': 2748,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '246714911',
      'twitterName': 'EdithGraf',
      'personId': 1295,
      'name': 'Edith Graf-Litscher',
      'number': 2652,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '226922317',
      'twitterName': 'ChristaMarkwald',
      'personId': 1139,
      'name': 'Christa Markwalder',
      'number': 2614,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '196646702',
      'twitterName': 'PirminBischof',
      'personId': 3871,
      'name': 'Pirmin Bischof',
      'number': 2674,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': '72560162',
      'twitterName': 'Violapamherd',
      'personId': 1288,
      'name': 'Viola Amherd',
      'number': 2646,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '50262858',
      'twitterName': 'MarcoRomanoPPD',
      'personId': 4120,
      'name': 'Marco Romano',
      'number': 3025,
      'council': 'NR',
      'party': 'CVP',
    },
    {
      'id': '14077586',
      'twitterName': 'bastiengirod',
      'personId': 3882,
      'name': 'Bastien Girod',
      'number': 2685,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': '21436172',
      'twitterName': 'cedricwermuth',
      'personId': 4057,
      'name': 'Cédric Wermuth',
      'number': 2759,
      'council': 'NR',
      'party': 'SP',
    },
    {
      'id': '2832533567',
      'twitterName': 'RiederBeat',
      'personId': 4204,
      'name': 'Beat Rieder',
      'number': 3105,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': '14675346',
      'twitterName': 'bglaettli',
      'personId': 4093,
      'name': 'Balthasar Glättli',
      'number': 3003,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': '3246291543',
      'twitterName': 'danieljositsch',
      'personId': 3891,
      'name': 'Daniel Jositsch',
      'number': 2694,
      'council': 'SR',
      'party': 'SP',
    },
    {
      'id': '556256043',
      'twitterName': 'SaSollberger',
      'personId': 4173,
      'name': 'Sandra Sollberger',
      'number': 3095,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '182760916',
      'twitterName': 'FrickerJonas',
      'personId': 4185,
      'name': 'Jonas Fricker',
      'number': 3072,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': '816301993799155712',
      'twitterName': 'Chrige_Haesler',
      'personId': 4149,
      'name': 'Christine Häsler',
      'number': 3051,
      'council': 'NR',
      'party': 'GPS',
    },
    {
      'id': '26531313',
      'twitterName': 'lukasreimann',
      'personId': 3901,
      'name': 'Lukas Reimann',
      'number': 2704,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '256863130',
      'twitterName': 'udcvr64',
      'personId': 4154,
      'name': 'Jean-Luc Addor',
      'number': 3055,
      'council': 'NR',
      'party': 'SVP',
    },
    {
      'id': '1947128240',
      'twitterName': 'Beat_Vonlanthen',
      'personId': 4205,
      'name': 'Beat Vonlanthen',
      'number': 3106,
      'council': 'SR',
      'party': 'CVP',
    },
    {
      'id': '3240586961',
      'twitterName': 'ThierryBurkart',
      'personId': 4189,
      'name': 'Thierry Burkart',
      'number': 3065,
      'council': 'NR',
      'party': 'FDP',
    },
    {
      'id': '3130690545',
      'twitterName': 'QuadrantiR',
      'personId': 4066,
      'name': 'Rosmarie Quadranti',
      'number': 2779,
      'council': 'NR',
      'party': 'BDP',
    },
    {
      'id': '113616426',
      'twitterName': 'BernhardGuhl',
      'personId': 4082,
      'name': 'Bernhard Guhl',
      'number': 2785,
      'council': 'NR',
      'party': 'BDP',
    },
    {
      'id': '1017350089',
      'twitterName': 'Yvette67Yvette',
      'personId': 3876,
      'name': 'Yvette Estermann',
      'number': 2679,
      'council': 'NR',
      'party': 'SVP',
    },
  ]
